sudo: false
dist: trusty
language: python
python: 2.7

env:
  - SCRIPT=lint
  - SCRIPT=tools/travis/build.py

matrix:
  allow_failures:
    - env: SCRIPT=tools/travis/build.py

before_install:
  git fetch --unshallow

script:
  - python $SCRIPT

cache:
  directories:
    - $HOME/.cache/pip
    - tools/apiclient
    - tools/w3ctestlib
